---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callback-server
  labels:
    app: callback-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callback-server
  template:
    metadata:
      labels:
        app: callback-server
    spec:
      containers:
      - name: callback-server
        image: informaticsmatters/data-manager-job-callback-server:latest
        ports:
        - containerPort: 5000
