---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: callback-server

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: callback-server-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['im-core-unrestricted']

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: callback-server
roleRef:
  kind: Role
  name: callback-server-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: callback-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callback-server
  labels:
    app: callback-server
spec:
  selector:
    matchLabels:
      app: callback-server
  template:
    metadata:
      labels:
        app: callback-server
    spec:
      serviceAccountName: callback-server
      containers:
      - name: callback-server
        image: informaticsmatters/data-manager-job-callback-server:latest
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: callback-server
spec:
  selector:
    app: callback-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
